cronJobs:
  - name: resetPwdExpiredToken
    id: 1
    cronTime: "*/15 * * * *"
    callback: Job resetPwdExpiredToken  executed
  - name: deleteAllCompanies
    id: 2
    cronTime: "*/15 * * * *"
    callback: Job deleteAllCompanies executed